# Generated by Django 3.1 on 2020-10-19 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showcase',
            name='image',
            field=models.FilePathField(path='images/'),
        ),
    ]
