# Generated by Django 3.1 on 2020-10-19 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0002_auto_20201019_0446'),
        ('showcase', '0002_auto_20201019_0447'),
    ]

    operations = [
    ]
